# Add application configuration variables here, as shown below.
#
TWITTER_CONSUMER_KEY: GwO0Kiy8EobqPQLWpuaumIWtn
TWITTER_CONSUMER_SECRET:  KHaHqMP2BLKqY7udIV4QJUsXguAdr11Tcqzk2f6a4oXgI6gCrC
AWS_BUCKET_NAME:  buckleys78_portfolio
AWS_ACCESS_KEY_ID:  AKIAIOCO3UAZIZTZRX5Q
AWS_SECRET_ACCESS_KEY:  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
