# Add application configuration variables here, as shown below.
#
TWITTER_CONSUMER_KEY: WmLbjFenM8eiES7mIhd3tHRwy 
TWITTER_CONSUMER_SECRET:  cauc7lhO6ZoKBMcn1UPTGaeMT7pCAWJNl5PDZcsj46AYjUd0oL 
AWS_BUCKET_NAME:  buckleys78_portfolio
AWS_ACCESS_KEY_ID:  AKIAIARTHEXL6XMNEL7A
AWS_SECRET_ACCESS_KEY:  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
